language: rust
rust:
    - nightly
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y libzmq3 libzmq3-dev
cache: cargo
script:
    - cargo build --verbose --all
    - cargo test --verbose --all
