[package]
name = "benita"
version = "0.0.1"
authors = ["Joaquín R <globojorro@gmail.com>"]

[dependencies]
error-chain = "~0.10.0"
ezo-rtd = { git = "https://github.com/saibatizoku/ezo-rtd-rs.git", branch = "master" }
i2cdev = "0.3.1"
sysfs_gpio = "0.5"

[profile.release]
lto = true
