[package]
name = "benita"
version = "0.0.1"
authors = ["Joaquín R <globojorro@gmail.com>"]

[dependencies]
chrono = "0.4.0"
error-chain = "~0.10.0"
ezo_ec = { git = "https://github.com/saibatizoku/ezo-ec-rs.git", branch = "master" }
ezo_ph = { git = "https://github.com/saibatizoku/ezo-ph-rs.git", branch = "master" }
ezo_rtd = { git = "https://github.com/saibatizoku/ezo-rtd-rs.git", branch = "master" }
i2cdev = "0.3.1"
neuras = { git = "https://github.com/saibatizoku/neuras.git", branch = "master" }
sensehat = { git = "https://github.com/shaunmulligan/sensehat-rs.git", branch = "master" }
sysfs_gpio = "0.5"
zmq = "0.8"

[profile.release]
lto = true
